version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5445:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
